question_data = [
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Goldfish have a memory span of only three seconds.", "answer": "False"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain from base to peak.", "answer": "False"},
    {"text": "An adult human body has 206 bones.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Humans share about 98% of their DNA with chimpanzees.", "answer": "True"},
    {"text": "Sound travels faster in air than in water.", "answer": "False"},
    {"text": "A day on Mercury is longer than a year on Mercury.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "Water boils at 100°C at sea level.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The human heart beats over 100,000 times a day.", "answer": "True"}
]